[package]
name = "flatten-vector-1-2021"
version = "0.1.0"
authors = ["Yacob (Kobi) Cohen-Arazi <kobic@qti.qualcomm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.7.3"
